# ------------------------------------------------------------------------------


- name: Check kubectx status
  ansible.builtin.shell: |
    if [ "$(kubectx --version)" != "{{ kubectx_version }}" ]; then
      echo 'install required'
    fi
  register: kubectx_status
  changed_when: "'install required' in task.stdout"


# ------------------------------------------------------------------------------


- name: Download archive to tmp
  when: "'install required' in kubectx_status.stdout"
  ansible.builtin.get_url:
    url: https://github.com/ahmetb/kubectx/releases/download/v{{ kubectx_version }}/kubectx_v{{ kubectx_version }}_linux_{{ kubectx_arch }}.tar.gz
    dest: /tmp/kubectx-{{ kubectx_version }}.tar.gz
    force: true
  become: true

- name: Create temporary dir for unpacked archive
  when: "'install required' in kubectx_status.stdout"
  ansible.builtin.shell: |
    rm -rf /tmp/kubectx-{{ kubectx_version }} || true
    mkdir -p /tmp/kubectx-{{ kubectx_version }}
  become: true

- name: Unarchive archive to temporary dir
  when: "'install required' in kubectx_status.stdout"
  ansible.builtin.unarchive:
    src: /tmp/kubectx-{{ kubectx_version }}.tar.gz
    dest: /tmp/kubectx-{{ kubectx_version }}/
    remote_src: true
  become: true

- name: Copy file with owner and permissions
  when: "'install required' in kubectx_status.stdout"
  ansible.builtin.copy:
    src: /tmp/kubectx-{{ kubectx_version }}/kubectx
    dest: /usr/local/bin/kubectx
    mode: u=rwx,g=rx,o=rx
    owner: root
    group: root
    remote_src: true
  become: true


# ------------------------------------------------------------------------------
