- name: Download archive to tmp
  get_url:
    url: https://github.com/ahmetb/kubectx/releases/download/v{{ kubectx_version }}/kubectx_v{{ kubectx_version }}_linux_{{ kubectx_arch }}.tar.gz
    dest: /tmp/kubectx-{{ kubectx_version }}.tar.gz
  become: true

- name: Create temporary dir for unpacked archive
  file:
    path: /tmp/kubectx-{{ kubectx_version }}
    state: directory
  become: true

- name: Unarchive archive to temporary dir
  unarchive:
    src: /tmp/kubectx-{{ kubectx_version }}.tar.gz
    dest: /tmp/kubectx-{{ kubectx_version }}/
    remote_src: true
  become: true

- name: Copy file with owner and permissions
  copy:
    src: /tmp/kubectx-{{ kubectx_version }}/kubectx
    dest: /usr/local/bin/kubectx
    mode: u=rwx,g=rx,o=rx
    owner: root
    group: root
    remote_src: true
  become: true
