- name: Download archive to tmp
  get_url:
    url: https://github.com/ahmetb/kubectx/releases/download/v{{ kubectx_version }}/kubens_v{{ kubectx_version }}_linux_{{ kubectx_arch }}.tar.gz
    dest: /tmp/kubens-{{ kubectx_version }}.tar.gz
  become: true

- name: Create temporary dir for unpacked archive
  file:
    path: /tmp/kubens-{{ kubectx_version }}
    state: directory
  become: true

- name: Unarchive archive to temporary dir
  unarchive:
    src: /tmp/kubens-{{ kubectx_version }}.tar.gz
    dest: /tmp/kubens-{{ kubectx_version }}/
    remote_src: true
  become: true

- name: Copy file with owner and permissions
  copy:
    src: /tmp/kubens-{{ kubectx_version }}/kubens
    dest: /usr/local/bin/kubens
    mode: u=rwx,g=rx,o=rx
    owner: root
    group: root
    remote_src: true
  become: true

- name: Download bash completion script and place it
  get_url:
    url: https://raw.githubusercontent.com/ahmetb/kubectx/v{{ kubectx_version }}/completion/kubens.bash
    dest: /usr/share/bash-completion/completions/kubens
    mode: u=rw,g=r,o=r
    owner: root
    group: root
    force: true
  become: true
